---
title: "Powerlifting Project"
author: "Will Maher"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(caTools)
library(skimr)
library(rpart)
library(caTools)
library(skimr)
library(glmnet)
library(pROC)
```

```{r loading_data}
pwr_data <- read_csv("powerlifting_data.csv")
```

```{r wrangling_data}
# wrangling and getting rid of unessecary columns
usapl_data <- pwr_data %>% 
    filter(Federation == "USAPL", 
           Equipment == "Raw",
           Event == "SBD", 
           Sanctioned == "Yes") %>% 
    select(Name, Sex, Squat1Kg, Bench1Kg, Deadlift1Kg, TotalKg, Date) %>% 
    drop_na() 

# only 2023
usapl_data$Date <- as.Date(usapl_data$Date)
usapl_data <- usapl_data %>% 
    filter(year(Date) == 2023)
```


```{r descriptive_analysis}
mean(usapl_data$Bench1Kg)
mean(usapl_data$Squat1Kg)
mean(usapl_data$Deadlift1Kg)

sd(usapl_data$Bench1Kg)
sd(usapl_data$Squat1Kg)
sd(usapl_data$Deadlift1Kg)

sex_distribution <- usapl_data %>% count(Sex)
ggplot(sex_distribution, aes(x = Sex, y = n, fill = Sex)) +
    geom_bar(stat = "identity") +
    labs(title = "Frequency Distribution of Sex", x = "Sex", y = "Frequency") +
    theme(plot.title = element_text(hjust = 0.5))
ggplot(usapl_data, aes(x = Sex, y = TotalKg, fill = Sex)) +
    geom_boxplot() +
    labs(title = "Distribution of TotalKg Across Sex", x = "Sex", y = "TotalKg") +
    theme(plot.title = element_text(hjust = 0.5))

#area under ROC curve for predicting target
usapl_data %>% 
    select(TotalKg, where(is.numeric)) %>% 
    filterVarImp(.$TotalKg) %>%
    arrange(desc(Overall)) %>%
    as.data.frame() %>%
    tibble::rownames_to_column(var = "Variable") %>%
    rename("Area Under ROC Curve" = 2)
#Pearson correlation
usapl_data %>% 
    summarise(across(where(is.numeric), ~ abs(cor(.,TotalKg, use = "complete.obs")))) %>% 
    unlist %>% 
    sort(decreasing = TRUE) %>%
    as.data.frame() %>%
    tibble::rownames_to_column(var = "Variable") %>%
    rename(Correlation = 2)
#Lowess R^2
usapl_data %>% 
    filter(!is.na(TotalKg)) %>% 
    select(where(is.numeric)) %>% 
    filterVarImp(.$TotalKg, nonpara = TRUE) %>% 
    arrange(desc(Overall)) %>%
    as.data.frame() %>%
    tibble::rownames_to_column(var = "Variable") %>%
    rename("Lowess R^2" = 2)

missing_values_excluded <- usapl_data %>%
  select(-Sex, -Name, -Date) %>%
  summarize_all(~ sum(is.na(.))) %>%
  gather(key = "Variable", value = "MissingValues")
ggplot(missing_values_excluded, aes(x = Variable, y = MissingValues, fill = Variable)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(x = "Variable", y = "Count of Missing Values", title = "Missing Values per Variable") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
usapl_data2 <- pwr_data %>% 
    filter(Federation == "USAPL",
           Equipment == "Raw",
           Event == "SBD",
           Sanctioned == "Yes") %>% 
    select(Name, Sex, 
           Squat1Kg, Squat2Kg, Squat3Kg, Best3SquatKg,
           Bench1Kg, Bench2Kg, Bench3Kg, Best3BenchKg, 
           Deadlift1Kg, Deadlift2Kg, Deadlift3Kg, Best3DeadliftKg, 
           TotalKg, Date, Age, AgeClass, Division, BodyweightKg, 
           WeightClassKg) %>% 
    drop_na()

usapl_data2$Date <- as.Date(usapl_data2$Date)
usapl_data2 <- usapl_data2 %>% 
    filter(year(Date) == 2023) 

    
```


```{r partitioning}
set.seed(1234)
split = sample.split(usapl_data$TotalKg, SplitRatio = 0.5)

usapl_data %>% 
    filter(split) %>% skim

usapl_data %>% 
    filter(!split) %>% skim

data <- as.data.frame(usapl_data)
```


```{r linear_model}
full <- lm(TotalKg ~ Squat1Kg + Bench1Kg + Deadlift1Kg, data = data[split,])
summary(full)
```


```{r lasso}
y <- data[split,]$TotalKg
x <- data.matrix(data[split,][,c('Squat1Kg','Bench1Kg','Deadlift1Kg')])

cv_model <- cv.glmnet(x, y, alpha = 1)
best_lambda <- cv_model$lambda.min

final_lasso <- glmnet(x, y, alpha = 1, lambda = best_lambda)
coef(final_lasso)
```


```{r ridge}
# using glmnet
x <- data.matrix(data[split,][,c('Squat1Kg','Bench1Kg','Deadlift1Kg')])
y <- data[split,][,'TotalKg']

lambda_seq <- 10^seq(2, -2, by = -.1)
ridge_fit <- glmnet(x, y, alpha = 0, lambda = lambda_seq)

ridge_cv <- cv.glmnet(x, y, alpha = 0, lambda = lambda_seq)
best_lambda_ridge <- ridge_cv$lambda.min

best_fit_ridge <- ridge_cv$glmnet.fit


final_ridge <- glmnet(x, y, alpha = 0, lambda = best_lambda_ridge)
coef(final_ridge)
```


```{r}
# linear



```

